[package]
name = "retry-cli"
version = "0.0.2"
authors = ["Brian Caswell <bmc@shmoo.com>"]
description = "retry commands with automatic backoff"
repository = "https://github.com/demoray/retry-cli"
license = "MIT"
edition = "2021"
categories = ["command-line-utilities"]

[[bin]]
name = "retry"
path = "src/main.rs"

[dependencies]
exponential-backoff = "1.2"
clap = { version = "4.5", features = ["derive"] }
thiserror = "1.0"
