name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - run: rustup update
      shell: bash
    - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6
    - uses: baptiste0928/cargo-install@8195d4f734a149db85385bb4102b42efcd373759
      with:
        crate: typos-cli
    - run: eng/build.sh
      shell: bash